version: '3'

services:

  # Backend / API
  backend:
    container_name: backend
    build: ../Backend
    volumes:
      - ../backend/toangvl/:/user/src/app/
    restart: always
    env_file:
      - ./environment/development.env
    ports:
      - '80:80'
    depends_on:
      - database
    networks:
      - toangvlnet
  
  # Database mysql
  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - '32000:3306'
    env_file:
      - ./environment/development.env
    networks:
      - toangvlnet

  # PHP admin just for dev
  phpmyadmin:
    container_name: phpmyadmin
    depends_on: 
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - ./environment/development.env
    networks:
      - toangvlnet

networks:
  toangvlnet:

