version: '3'

services:

  # Backend / API
  backend:
    image: api
    build: ../Backend
    volumes:
      - ../backend/toangvl/:/user/src/app/
    restart: always
    env_file:
      - ./environment/development.env
    ports:
      - '4201:80'
    depends_on:
      - database
    networks:
      - toangvlnet
  
  # Database mysql
  database:
    image: mongo:latest
    container_name: database
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./environment/development.env
    networks:
      - toangvlnet
  
networks:
  toangvlnet:

