version: '3'

services:
  frontend:
    image: "${FRONTEND_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    restart: always
    env_file: production.env
    ports:
      - '80:80'
    networks:
      - toangvlnet

networks:
  toangvlnet:

volumes:
  static_volume:
  media_volume:


