name: Build-BE
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo haha
    - run: echo haha
