name: Production backend building job
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ECR_ID: ${{ secrets.AWS_ECR_ID }}
  BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}

jobs:
  # Building backend and pushing image to AWS ECR
  build:
    name: Building backend and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:

    - name: Setup ECR
      run: |
        aws ecr get-login-password \
        | docker login \
            --password-stdin \
            --username AWS \
            "${AWS_ECR_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

    - name: Build and tag the image
      run: |
        docker build \
          -t $BACKEND_IMAGE \
          -t $AWS_ECR_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_IMAGE ./Backend

    - name: Push image to ECR
      run: |
        docker push $AWS_ECR_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_IMAGE
     
  # Building backend pull image from AWS ECR and push to server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo DEPLOY BACKEND DOCKER IMAGE TO ECR AWS....
    