name: Production backend building job
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo BUID BACKEND DOCKER IMAGE TO ECR AWS....
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo BUID BACKEND DOCKER IMAGE TO ECR AWS....
    