name: Production backend building job
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ECR_ID: ${{ secrets.AWS_ECR_ID }}
  BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  # Building backend and pushing image to AWS ECR
  build:
    name: Building backend and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub Registry
      run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Build and tag the image
      run: |
        docker build -t $BACKEND_IMAGE -t $DOCKERHUB_USERNAME/toangvl:$BACKEND_IMAGE ./Backend

    - name: Push image to DockerHub
      run: |
        docker push $DOCKERHUB_USERNAME/toangvl:$BACKEND_IMAGE
     
  # Building backend pull image from AWS ECR and push to server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo DEPLOY BACKEND DOCKER IMAGE TO ECR AWS....
    